global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastory-backend'
    metrics_path: '/actuator/prometheus'
    dns_sd_configs:
      - names:
          - 'backend.fastory.local'
        type: 'A'
        port: 8080
